Request for updated documentation.
Hello,
The current documentation for netlify.toml results in this error:

<code>
2:23:01 PM: ────────────────────────────────────────────────────────────────
2:23:01 PM:   Configuration error                                           
2:23:01 PM: ────────────────────────────────────────────────────────────────
2:23:01 PM: ​
2:23:01 PM:   Error message
2:23:01 PM:   Plugin could not be found using local path: .//plugins/netlify-purge-cloudflare-on-deploy
2:23:01 PM:   Cannot find module './/plugins/netlify-purge-cloudflare-on-deploy'
2:23:01 PM:   Require stack:
2:23:01 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/build/src/utils/resolve.js
2:23:01 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/resolve.js
2:23:01 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/options.js
2:23:01 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/build/src/core/main.js
2:23:01 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/build/src/core/bin.js
</code>

This code worked for me:

<code>
npm i netlify-purge-cloudflare-on-deploy

[[plugins]]
package = "netlify-purge-cloudflare-on-deploy"
</code>